[platform_archives.'arm-none-eabi'.macos_aarch64]
url = "https://developer.arm.com/-/media/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-darwin-arm64-arm-none-eabi.tar.xz"
sha256 = "21a9e875250bcb0db8df4cb23dd43c94c00a1d3b98ecba9cdd6ed51586b12248"
add_prefix = "{{spaces.sysroot}}"
strip_prefix = "arm-gnu-toolchain-12.2.rel1-darwin-x86_64-arm-none-eabi"
link = "Hard"


[platform_archives.'arm-none-eabi'.macos_x86_64]
url = "https://developer.arm.com/-/media/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-darwin-x86_64-arm-none-eabi.tar.xz"
sha256 = "00c0eeb57ae92332f216151ac66df6ba17d2d3b306dac86f4006006f437b2902"
add_prefix = "{{spaces.sysroot}}"
strip_prefix = "arm-gnu-toolchain-12.2.rel1-darwin-x86_64-arm-none-eabi"
link = "Hard"

[env.vars]
"thumbv6m-none-eabi_search_path" = "v6-m/nofp"
"thumbv6m-none-eabi_c_flags" = "-mcpu=cortex-m0 -mthumb",
        },
        "thumbv7m-none-eabi" => Thumb {
            search_path: "v7-m/nofp",
            c_flags: " -mcpu=cortex-m3 -mthumb",
        },
        "thumbv7em-none-eabi" => Thumb {
            search_path: "v7e-m/nofp",
            c_flags: " -mcpu=cortex-m4 -mfloat-abi=soft -mthumb",
        },
        "thumbv7em-none-eabihf" => Thumb {
            search_path: "v7e-m+fp/hard",
            c_flags: " -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb",
        },
        "thumbv8m.base-none-eabi" => Thumb {
            search_path: "v8-m.base/nofp",
            c_flags: " -mcpu=cortex-m33 -mthumb",
        },
        "thumbv8m.main-none-eabi" => Thumb {
            search_path: "v7e-m.main/nofp",
            c_flags: " -mcpu=cortex-m33 -mthumb",
        },
        "thumbv8m.main-none-eabihf" => Thumb {
            search_path: "v8-m.main+fp/hard",
            c_flags: " -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mthumb",
        },
